{
 "title": "New dashboard Copy",
 "description": "3つバラバラ",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "テスト",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"exp\",\n    pod=~\"(checkout|email|payment).*\",\n    container=~\"checkout|payment|email\"\n  }[2m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "平均レイテンシpayment",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(\n    istio_request_duration_milliseconds_sum{\n      reporter=\"destination\",\n      source_workload=\"checkoutservice\",\n      destination_workload=\"paymentservice\"\n    }[5m]\n  )\n/\nincrease(\n    istio_request_duration_milliseconds_count{\n      reporter=\"destination\",\n      source_workload=\"checkoutservice\",\n      destination_workload=\"paymentservice\"\n    }[5m]\n  )",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(\n    istio_request_duration_milliseconds_sum{\n      reporter=\"source\",\n      source_workload=\"checkoutservice\",\n      destination_workload=\"paymentservice\"\n    }[5m]\n  )\n/\nincrease(\n    istio_request_duration_milliseconds_count{\n      reporter=\"source\",\n      source_workload=\"checkoutservice\",\n      destination_workload=\"paymentservice\"\n    }[5m]\n  )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "パーセンタイルEmail　r=destination",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    increase(\n      istio_request_duration_milliseconds_bucket{\n        source_workload=\"checkoutservice\",\n        destination_workload=\"emailservice\",\n        reporter=\"destination\"\n      }[5m]\n    )\n  )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le) (\n    increase(\n      istio_request_duration_milliseconds_bucket{\n        source_workload=\"checkoutservice\",\n        destination_workload=\"emailservice\",\n        reporter=\"destination\"\n      }[5m]\n    )\n  )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le) (\n    increase(\n      istio_request_duration_milliseconds_bucket{\n        source_workload=\"checkoutservice\",\n        destination_workload=\"emailservice\",\n        reporter=\"destination\"\n      }[5m]\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "パーセンタイルPAYMANT r=destinaiton",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    increase(\n      istio_request_duration_milliseconds_bucket{\n        source_workload=\"checkoutservice\",\n        destination_workload=\"paymentservice\",\n        reporter=\"destination\"\n      }[5m]\n    )\n  )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le) (\n    increase(\n      istio_request_duration_milliseconds_bucket{\n        source_workload=\"checkoutservice\",\n        destination_workload=\"paymentservice\",\n        reporter=\"destination\"\n      }[5m]\n    )\n  )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le) (\n    increase(\n      istio_request_duration_milliseconds_bucket{\n        source_workload=\"checkoutservice\",\n        destination_workload=\"paymentservice\",\n        reporter=\"destination\"\n      }[5m]\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "パーセンタイルPAYMANT r=source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    increase(\n      istio_request_duration_milliseconds_bucket{\n        source_workload=\"checkoutservice\",\n        destination_workload=\"paymentservice\",\n        reporter=\"source\"\n      }[5m]\n    )\n  )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le) (\n    increase(\n      istio_request_duration_milliseconds_bucket{\n        source_workload=\"checkoutservice\",\n        destination_workload=\"paymentservice\",\n        reporter=\"source\"\n      }[5m]\n    )\n  )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le) (\n    increase(\n      istio_request_duration_milliseconds_bucket{\n        source_workload=\"checkoutservice\",\n        destination_workload=\"paymentservice\",\n        reporter=\"source\"\n      }[5m]\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "パーセンタイルEMAIL r=source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    increase(\n      istio_request_duration_milliseconds_bucket{\n        source_workload=\"checkoutservice\",\n        destination_workload=\"emailservice\",\n        reporter=\"source\"\n      }[10m]\n    )\n  )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le) (\n    increase(\n      istio_request_duration_milliseconds_bucket{\n        source_workload=\"checkoutservice\",\n        destination_workload=\"emailservice\",\n        reporter=\"source\"\n      }[10m]\n    )\n  )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le) (\n    increase(\n      istio_request_duration_milliseconds_bucket{\n        source_workload=\"checkoutservice\",\n        destination_workload=\"emailservice\",\n        reporter=\"source\"\n      }[10m]\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu利用量(podごと)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "#別々の描画\nsum by (pod) (\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"exp\",\n    pod=~\"(paymentservice|emailservice|checkoutservice)-.*\",\n    container!=\"\"\n  }[10m])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "#３つ合計の描画\nsum(\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"exp\",\n    pod=~\"(paymentservice|emailservice|checkoutservice)-.*\",\n    container!=\"\"\n  }[10m])\n)\n",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "cpu利用量（コンテナごと）",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by(container)(\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"exp\",\n    pod=~\"checkout.*\",\n    container=~\"checkout|email|payment\"\n  }[10m])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(container)(\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"exp\",\n    pod=~\"payment.*\",\n    container=~\"payment|email\"\n  }[10m])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(container)(\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"exp\",\n    pod=~\"email.*\",\n    container=~\"email\"\n  }[10m])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"exp\",\n    pod=~\"(checkout|email|payment).*\",\n    container=~\"checkout|payment|email\"\n  }[10m])\n)",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "envoyの利用cpu",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by(container)(\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"exp\",\n    pod=~\"checkoutservice-.*\",\n    container=~\"istio-proxy\"\n  }[10m])\n)",
     "legendFormat": "checkout-istio"
    },
    {
     "expr": "sum by(container)(\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"exp\",\n    pod=~\"paymentservice-.*\",\n    container=~\"istio-proxy\"\n  }[10m])\n)",
     "legendFormat": "payment-istio"
    },
    {
     "expr": "sum by(container)(\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"exp\",\n    pod=~\"email.*\",\n    container=~\"istio-proxy\"\n  }[10m])\n)",
     "legendFormat": "email-istio"
    },
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"exp\",\n    pod=~\"(checkout|email|payment).*\",\n    container=\"istio-proxy\"\n  }[10m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "コンテナ平均レイテンシemail",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "(\n  increase(grpc_client_latency_seconds_sum[10m])\n  /\n  increase(grpc_client_latency_seconds_count[10m])\n) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "平均レイテンシemail",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "increase(\n    istio_request_duration_milliseconds_sum{\n      reporter=\"destination\",\n      source_workload=\"checkoutservice\",\n      destination_workload=\"emailservice\"\n    }[10m]\n  )\n/\nincrease(\n    istio_request_duration_milliseconds_count{\n      reporter=\"destination\",\n      source_workload=\"checkoutservice\",\n      destination_workload=\"emailservice\"\n    }[10m]\n  )",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(\n    istio_request_duration_milliseconds_sum{\n      reporter=\"source\",\n      source_workload=\"checkoutservice\",\n      destination_workload=\"emailservice\"\n    }[10m]\n  )\n/\nincrease(\n    istio_request_duration_milliseconds_count{\n      reporter=\"source\",\n      source_workload=\"checkoutservice\",\n      destination_workload=\"emailservice\"\n    }[10m]\n  )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "podへのリクエスト回数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum by(pod)(\n    istio_requests_total{\n      destination_workload=\"paymentservice\",\n      destination_workload_namespace=\"exp\",\n      reporter=\"destination\"\n    }\n  )",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(pod)(\n    istio_requests_total{\n      destination_workload=\"checkoutservice\",\n      destination_workload_namespace=\"exp\",\n      reporter=\"destination\"\n    }\n  )",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(pod)(\n    istio_requests_total{\n      destination_workload=\"emailservice\",\n      destination_workload_namespace=\"exp\",\n      reporter=\"destination\"\n    }\n  )",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(pod)(\n  rate(\n    istio_requests_total{\n      destination_workload=\"paymentservice\",\n      destination_workload_namespace=\"exp\",\n      reporter=\"destination\"\n    }[1m]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "メモリ使用量（コンテナごと）",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum by(container)(\n  rate(container_memory_working_set_bytes{\n    namespace=\"exp\",\n    pod=~\"checkout.*\",\n    container=~\"checkout|email|payment\"\n  }[1m])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(pod, container)(\n  rate(container_memory_working_set_bytes{\n    namespace=\"exp\",\n    pod=~\"payment.*\",\n    container=~\"payment\"\n  }[1m])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(container)(\n  rate(container_memory_working_set_bytes{\n    namespace=\"exp\",\n    pod=~\"email.*\",\n    container=~\"email\"\n  }[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "受信byte量(pod単位)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum by (pod)(\n  rate(container_network_receive_bytes_total{\n    namespace=\"exp\",\n    pod=~\"(paymentservice|emailservice|checkoutservice)-.*\"\n  }[1m])\n  )",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (\n  rate(container_network_receive_bytes_total{\n    namespace=\"exp\",\n    pod=~\"(paymentservice|emailservice|checkoutservice)-.*\"\n  }[1m])\n  )",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}