{
 "title": "New dashboard",
 "description": "3つバラバラ",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "envoyの利用cpu",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(container)(\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"exp\",\n    pod=~\"checkout.*\",\n    container=~\"istio-proxy\"\n  }[2m])\n)",
     "legendFormat": "checkout-istio"
    },
    {
     "expr": "sum by(container)(\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"exp\",\n    pod=~\"payment.*\",\n    container=~\"istio-proxy\"\n  }[2m])\n)",
     "legendFormat": "payment-istio"
    },
    {
     "expr": "sum by(container)(\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"exp\",\n    pod=~\"email.*\",\n    container=~\"istio-proxy\"\n  }[2m])\n)",
     "legendFormat": "email-istio"
    },
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"exp\",\n    pod=~\"(checkout|email|payment).*\",\n    container=\"istio-proxy\"\n  }[2m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu利用量（コンテナごと）",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(container)(\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"exp\",\n    pod=~\"checkout.*\",\n    container=~\"checkout|email|payment\"\n  }[2m])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(container)(\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"exp\",\n    pod=~\"payment.*\",\n    container=~\"payment|email\"\n  }[2m])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(container)(\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"exp\",\n    pod=~\"email.*\",\n    container=~\"email\"\n  }[2m])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"exp\",\n    pod=~\"checkout.*|payment.*|email.*\",\n    container=~\"checkout|payment|email\"\n  }[2m])\n)",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "podへのリクエスト回数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(pod)(\n    istio_requests_total{\n      destination_workload=\"paymentservice\",\n      destination_workload_namespace=\"exp\",\n      reporter=\"destination\"\n    }\n  )",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(pod)(\n    istio_requests_total{\n      destination_workload=\"checkoutservice\",\n      destination_workload_namespace=\"exp\",\n      reporter=\"destination\"\n    }\n  )",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(pod)(\n    istio_requests_total{\n      destination_workload=\"emailservice\",\n      destination_workload_namespace=\"exp\",\n      reporter=\"destination\"\n    }\n  )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu利用量(podごと)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "#別々の描画\nsum by (pod) (\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"exp\",\n    pod=~\"(paymentservice|emailservice|checkoutservice)-.*\",\n    container!=\"\"\n  }[2m])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "#３つ合計の描画\nsum(\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"exp\",\n    pod=~\"(paymentservice|emailservice|checkoutservice)-.*\",\n    container!=\"\"\n  }[2m])\n)\n",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "メモリ使用量（コンテナごと）",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(container)(\n  rate(container_memory_working_set_bytes{\n    namespace=\"exp\",\n    pod=~\"checkout.*\",\n    container=~\"checkout|email|payment\"\n  }[1m])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(pod, container)(\n  rate(container_memory_working_set_bytes{\n    namespace=\"exp\",\n    pod=~\"payment.*\",\n    container=~\"payment\"\n  }[1m])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(container)(\n  rate(container_memory_working_set_bytes{\n    namespace=\"exp\",\n    pod=~\"email.*\",\n    container=~\"email\"\n  }[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "テスト",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "#rate(container_cpu_usage_seconds_total{\n#    namespace=\"exp\",\n#    pod=~\"(paymentservice|emailservice|checkoutservice)-.*\"\n#  }[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "\n  　rate(\n    container_cpu_usage_seconds_total{\n   　   namespace=\"exp\",\n      pod=~\"(checkoutservice)-.*\"\n      #container=\"checkout\"\n    }[1m]\n  )",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (source_workload, destination_workload) (\n  rate(istio_request_duration_milliseconds_sum{\n    source_workload=\"frontend\",\n    destination_workload=\"productcatalogservice\"\n  }[1m])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "istio_request_duration_milliseconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "受信byte量(pod単位)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (pod)(\n  rate(container_network_receive_bytes_total{\n    namespace=\"exp\",\n    pod=~\"(paymentservice|emailservice|checkoutservice)-.*\"\n  }[1m])\n  )",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (\n  rate(container_network_receive_bytes_total{\n    namespace=\"exp\",\n    pod=~\"(paymentservice|emailservice|checkoutservice)-.*\"\n  }[1m])\n  )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory2",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 3, "y": 33 },
   "targets": [
    {
     "expr": "#別々の描画\nsum by (pod) (\n  rate(container_memory_usage_bytes{\n    namespace=\"exp\",\n    pod=~\"(paymentservice|emailservice|checkoutservice)-.*\"\n  }[5m])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "#合計\nsum (\n  rate(container_memory_usage_bytes{\n    namespace=\"exp\",\n    pod=~\"(paymentservice|emailservice|checkoutservice)-.*\"\n  }[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}